### ISSUE TITLE
search command syntax problem

### ISSUE THREAD

**Issue by jasnab** [piotrmurach/github_cli#18]
Hi, 

what is correct syntax for "search" command

when I have tried "gcli search repo apt"  I got fatal error, wrong number of arguments.... 
If I put "gcli search apt-cookbook apt" I get cannot find command apt

I'd really need help here. 

Thanks

**Comment by grosser** [comment]
```
Fatal error has occurred. Wrong number of arguments (0 for 1). Expected `q` as required arguments, but got ``.ArgumentError: Wrong number of arguments (0 for 1). Expected `q` as required arguments, but got ``.
/opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/github_api-0.13.0/lib/github_api/api/arguments.rb:224:in `check_requirement!'
/opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/github_api-0.13.0/lib/github_api/api/arguments.rb:164:in `parse_hash'
/opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/github_api-0.13.0/lib/github_api/api/arguments.rb:96:in `parse'
/opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/github_api-0.13.0/lib/github_api/api.rb:251:in `arguments'
/opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/github_api-0.13.0/lib/github_api/client/search.rb:70:in `repos'
/opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/github_api-0.13.0/lib/github_api/api.rb:224:in `block in execute'
/opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/github_api-0.13.0/lib/github_api/api.rb:211:in `run_callbacks'
/opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/github_api-0.13.0/lib/github_api/api.rb:223:in `execute'
/opt/boxen/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/github_api-0.13.0/lib/github_api/api.rb:183:in `block in method_added'
```

**Comment by grosser** [comment]
@peter-murach

**Comment by peter-murach** [comment]
@grosser The truth is that `github_api` gem is a actively maintained project but this library hasn't been updated by me since 2013. Now, I'm planning to resurrect this project and update it. However, this is a bit of undertaking and I need to plan my time. I will prioritize search function but probably PR would make the process quicker.

**Comment by grosser** [comment]
FYI I wrote this little script to help me do the searching I wanted to do, so I'm good for now :)
