### ISSUE TITLE
gcli pull create -> Invalid request: "base", "head" weren't supplied.

### ISSUE THREAD

**Issue by Apollon77** [piotrmurach/github_cli#28]
I tried to issue an gcli pull create <use> <repo> command and the error was as follows:

```Fatal error has occurred. POST https://api.github.com/repos/xxxx/xxxxx/pulls?access_token=xxxxxxx: 422 - Invalid request.

"base", "head" weren't supplied.
See: https://developer.github.com/v3/pulls/#create-a-pull-requestGithub::Error::UnprocessableEntity: POST https://api.github.com/repos/xxxx/xxxx/pulls?access_token=xxxxxx: 422 - Invalid request.

"base", "head" weren't supplied.
See: https://developer.github.com/v3/pulls/#create-a-pull-request
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_api-0.14.5/lib/github_api/response/raise_error.rb:18:in `on_complete'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_api-0.14.5/lib/github_api/request/basic_auth.rb:32:in `call'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_api-0.14.5/lib/github_api/request/oauth2.rb:24:in `call'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/faraday-0.9.2/lib/faraday/request/multipart.rb:14:in `call'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_api-0.14.5/lib/github_api/request/jsonize.rb:23:in `call'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_api-0.14.5/lib/github_api/request.rb:69:in `call'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_api-0.14.5/lib/github_api/request/verbs.rb:35:in `post_request'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_api-0.14.5/lib/github_api/client/pull_requests.rb:88:in `create'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_api-0.14.5/lib/github_api/api.rb:227:in `block in execute'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_api-0.14.5/lib/github_api/api.rb:214:in `run_callbacks'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_api-0.14.5/lib/github_api/api.rb:226:in `execute'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_api-0.14.5/lib/github_api/api.rb:186:in `block in method_added'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/lib/github_cli/apis/pull_request.rb:22:in `block in create'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/lib/github_cli/api.rb:64:in `call'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/lib/github_cli/api.rb:64:in `block in output'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/lib/github_cli/dsl.rb:19:in `on_error'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/lib/github_cli/api.rb:63:in `output'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/lib/github_cli/apis/pull_request.rb:21:in `create'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/lib/github_cli/commands/pull_requests.rb:42:in `create'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/lib/github_cli/vendor/thor/command.rb:27:in `run'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/lib/github_cli/vendor/thor/invocation.rb:120:in `invoke_command'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/lib/github_cli/vendor/thor.rb:363:in `dispatch'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/lib/github_cli/vendor/thor/invocation.rb:109:in `invoke'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/lib/github_cli/vendor/thor.rb:232:in `block in subcommand'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/lib/github_cli/vendor/thor/command.rb:27:in `run'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/lib/github_cli/vendor/thor/invocation.rb:120:in `invoke_command'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/lib/github_cli/vendor/thor.rb:363:in `dispatch'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/lib/github_cli/vendor/thor/base.rb:438:in `start'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/bin/gcli:9:in `block in <top (required)>'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/lib/github_cli/dsl.rb:19:in `on_error'
/Users/ingof/.rvm/gems/ruby-2.2.6/gems/github_cli-0.6.2/bin/gcli:9:in `<top (required)>'
/Users/ingof/.rvm/gems/ruby-2.2.6/bin/gcli:22:in `load'
/Users/ingof/.rvm/gems/ruby-2.2.6/bin/gcli:22:in `<main>'
/Users/ingof/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `eval'
/Users/ingof/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `<main>'```

**Comment by piotrmurach** [comment]
This library hasn't been updated in quite long time, I would be really surprised if things still worked fine. I'm hoping to update it soon but cannot guarantee any timelines.

**Comment by Apollon77** [comment]
In the end it works ... when you set all these parameters ... so only te error was a bit weired ... so I can also close this ...
